/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TroubleRouteImport } from './routes/trouble'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ShareRouteImport } from './routes/share'
import { Route as MyRouteImport } from './routes/my'
import { Route as MoreRouteImport } from './routes/more'
import { Route as MapRouteImport } from './routes/map'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TroubleSlugRouteImport } from './routes/trouble.$slug'
import { Route as LiveCodeRouteImport } from './routes/live.$code'

const TroubleRoute = TroubleRouteImport.update({
  id: '/trouble',
  path: '/trouble',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TroubleSlugRoute = TroubleSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TroubleRoute,
} as any)
const LiveCodeRoute = LiveCodeRouteImport.update({
  id: '/live/$code',
  path: '/live/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/events': typeof EventsRoute
  '/map': typeof MapRoute
  '/more': typeof MoreRoute
  '/my': typeof MyRoute
  '/share': typeof ShareRoute
  '/stats': typeof StatsRoute
  '/trouble': typeof TroubleRouteWithChildren
  '/live/$code': typeof LiveCodeRoute
  '/trouble/$slug': typeof TroubleSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/events': typeof EventsRoute
  '/map': typeof MapRoute
  '/more': typeof MoreRoute
  '/my': typeof MyRoute
  '/share': typeof ShareRoute
  '/stats': typeof StatsRoute
  '/trouble': typeof TroubleRouteWithChildren
  '/live/$code': typeof LiveCodeRoute
  '/trouble/$slug': typeof TroubleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/events': typeof EventsRoute
  '/map': typeof MapRoute
  '/more': typeof MoreRoute
  '/my': typeof MyRoute
  '/share': typeof ShareRoute
  '/stats': typeof StatsRoute
  '/trouble': typeof TroubleRouteWithChildren
  '/live/$code': typeof LiveCodeRoute
  '/trouble/$slug': typeof TroubleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/events'
    | '/map'
    | '/more'
    | '/my'
    | '/share'
    | '/stats'
    | '/trouble'
    | '/live/$code'
    | '/trouble/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/events'
    | '/map'
    | '/more'
    | '/my'
    | '/share'
    | '/stats'
    | '/trouble'
    | '/live/$code'
    | '/trouble/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/events'
    | '/map'
    | '/more'
    | '/my'
    | '/share'
    | '/stats'
    | '/trouble'
    | '/live/$code'
    | '/trouble/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EventsRoute: typeof EventsRoute
  MapRoute: typeof MapRoute
  MoreRoute: typeof MoreRoute
  MyRoute: typeof MyRoute
  ShareRoute: typeof ShareRoute
  StatsRoute: typeof StatsRoute
  TroubleRoute: typeof TroubleRouteWithChildren
  LiveCodeRoute: typeof LiveCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trouble': {
      id: '/trouble'
      path: '/trouble'
      fullPath: '/trouble'
      preLoaderRoute: typeof TroubleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trouble/$slug': {
      id: '/trouble/$slug'
      path: '/$slug'
      fullPath: '/trouble/$slug'
      preLoaderRoute: typeof TroubleSlugRouteImport
      parentRoute: typeof TroubleRoute
    }
    '/live/$code': {
      id: '/live/$code'
      path: '/live/$code'
      fullPath: '/live/$code'
      preLoaderRoute: typeof LiveCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TroubleRouteChildren {
  TroubleSlugRoute: typeof TroubleSlugRoute
}

const TroubleRouteChildren: TroubleRouteChildren = {
  TroubleSlugRoute: TroubleSlugRoute,
}

const TroubleRouteWithChildren =
  TroubleRoute._addFileChildren(TroubleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EventsRoute: EventsRoute,
  MapRoute: MapRoute,
  MoreRoute: MoreRoute,
  MyRoute: MyRoute,
  ShareRoute: ShareRoute,
  StatsRoute: StatsRoute,
  TroubleRoute: TroubleRouteWithChildren,
  LiveCodeRoute: LiveCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
