/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TroubleRouteImport } from './routes/trouble'
import { Route as TripRouteImport } from './routes/trip'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as MyRouteImport } from './routes/my'
import { Route as MoreRouteImport } from './routes/more'
import { Route as MapRouteImport } from './routes/map'
import { Route as LifeRouteImport } from './routes/life'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TroubleMapRouteImport } from './routes/trouble_.map'
import { Route as ResolvePostIdRouteImport } from './routes/resolve.$postId'
import { Route as PostTypeRouteImport } from './routes/post.$type'
import { Route as LiveCodeRouteImport } from './routes/live.$code'
import { Route as ActivitiesNewRouteImport } from './routes/activities.new'

const TroubleRoute = TroubleRouteImport.update({
  id: '/trouble',
  path: '/trouble',
  getParentRoute: () => rootRouteImport,
} as any)
const TripRoute = TripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeRoute = LifeRouteImport.update({
  id: '/life',
  path: '/life',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TroubleMapRoute = TroubleMapRouteImport.update({
  id: '/trouble_/map',
  path: '/trouble/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolvePostIdRoute = ResolvePostIdRouteImport.update({
  id: '/resolve/$postId',
  path: '/resolve/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostTypeRoute = PostTypeRouteImport.update({
  id: '/post/$type',
  path: '/post/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveCodeRoute = LiveCodeRouteImport.update({
  id: '/live/$code',
  path: '/live/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesNewRoute = ActivitiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ActivitiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/company': typeof CompanyRoute
  '/events': typeof EventsRoute
  '/life': typeof LifeRoute
  '/map': typeof MapRoute
  '/more': typeof MoreRoute
  '/my': typeof MyRoute
  '/school': typeof SchoolRoute
  '/share': typeof ShareRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/trip': typeof TripRoute
  '/trouble': typeof TroubleRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/live/$code': typeof LiveCodeRoute
  '/post/$type': typeof PostTypeRoute
  '/resolve/$postId': typeof ResolvePostIdRoute
  '/trouble/map': typeof TroubleMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/company': typeof CompanyRoute
  '/events': typeof EventsRoute
  '/life': typeof LifeRoute
  '/map': typeof MapRoute
  '/more': typeof MoreRoute
  '/my': typeof MyRoute
  '/school': typeof SchoolRoute
  '/share': typeof ShareRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/trip': typeof TripRoute
  '/trouble': typeof TroubleRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/live/$code': typeof LiveCodeRoute
  '/post/$type': typeof PostTypeRoute
  '/resolve/$postId': typeof ResolvePostIdRoute
  '/trouble/map': typeof TroubleMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/company': typeof CompanyRoute
  '/events': typeof EventsRoute
  '/life': typeof LifeRoute
  '/map': typeof MapRoute
  '/more': typeof MoreRoute
  '/my': typeof MyRoute
  '/school': typeof SchoolRoute
  '/share': typeof ShareRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/trip': typeof TripRoute
  '/trouble': typeof TroubleRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/live/$code': typeof LiveCodeRoute
  '/post/$type': typeof PostTypeRoute
  '/resolve/$postId': typeof ResolvePostIdRoute
  '/trouble_/map': typeof TroubleMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/announcements'
    | '/company'
    | '/events'
    | '/life'
    | '/map'
    | '/more'
    | '/my'
    | '/school'
    | '/share'
    | '/stats'
    | '/terms'
    | '/trip'
    | '/trouble'
    | '/activities/new'
    | '/live/$code'
    | '/post/$type'
    | '/resolve/$postId'
    | '/trouble/map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/announcements'
    | '/company'
    | '/events'
    | '/life'
    | '/map'
    | '/more'
    | '/my'
    | '/school'
    | '/share'
    | '/stats'
    | '/terms'
    | '/trip'
    | '/trouble'
    | '/activities/new'
    | '/live/$code'
    | '/post/$type'
    | '/resolve/$postId'
    | '/trouble/map'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/announcements'
    | '/company'
    | '/events'
    | '/life'
    | '/map'
    | '/more'
    | '/my'
    | '/school'
    | '/share'
    | '/stats'
    | '/terms'
    | '/trip'
    | '/trouble'
    | '/activities/new'
    | '/live/$code'
    | '/post/$type'
    | '/resolve/$postId'
    | '/trouble_/map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  CompanyRoute: typeof CompanyRoute
  EventsRoute: typeof EventsRoute
  LifeRoute: typeof LifeRoute
  MapRoute: typeof MapRoute
  MoreRoute: typeof MoreRoute
  MyRoute: typeof MyRoute
  SchoolRoute: typeof SchoolRoute
  ShareRoute: typeof ShareRoute
  StatsRoute: typeof StatsRoute
  TermsRoute: typeof TermsRoute
  TripRoute: typeof TripRoute
  TroubleRoute: typeof TroubleRoute
  LiveCodeRoute: typeof LiveCodeRoute
  PostTypeRoute: typeof PostTypeRoute
  ResolvePostIdRoute: typeof ResolvePostIdRoute
  TroubleMapRoute: typeof TroubleMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trouble': {
      id: '/trouble'
      path: '/trouble'
      fullPath: '/trouble'
      preLoaderRoute: typeof TroubleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip': {
      id: '/trip'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof TripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life': {
      id: '/life'
      path: '/life'
      fullPath: '/life'
      preLoaderRoute: typeof LifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trouble_/map': {
      id: '/trouble_/map'
      path: '/trouble/map'
      fullPath: '/trouble/map'
      preLoaderRoute: typeof TroubleMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolve/$postId': {
      id: '/resolve/$postId'
      path: '/resolve/$postId'
      fullPath: '/resolve/$postId'
      preLoaderRoute: typeof ResolvePostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$type': {
      id: '/post/$type'
      path: '/post/$type'
      fullPath: '/post/$type'
      preLoaderRoute: typeof PostTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$code': {
      id: '/live/$code'
      path: '/live/$code'
      fullPath: '/live/$code'
      preLoaderRoute: typeof LiveCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/new': {
      id: '/activities/new'
      path: '/new'
      fullPath: '/activities/new'
      preLoaderRoute: typeof ActivitiesNewRouteImport
      parentRoute: typeof ActivitiesRoute
    }
  }
}

interface ActivitiesRouteChildren {
  ActivitiesNewRoute: typeof ActivitiesNewRoute
}

const ActivitiesRouteChildren: ActivitiesRouteChildren = {
  ActivitiesNewRoute: ActivitiesNewRoute,
}

const ActivitiesRouteWithChildren = ActivitiesRoute._addFileChildren(
  ActivitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  CompanyRoute: CompanyRoute,
  EventsRoute: EventsRoute,
  LifeRoute: LifeRoute,
  MapRoute: MapRoute,
  MoreRoute: MoreRoute,
  MyRoute: MyRoute,
  SchoolRoute: SchoolRoute,
  ShareRoute: ShareRoute,
  StatsRoute: StatsRoute,
  TermsRoute: TermsRoute,
  TripRoute: TripRoute,
  TroubleRoute: TroubleRoute,
  LiveCodeRoute: LiveCodeRoute,
  PostTypeRoute: PostTypeRoute,
  ResolvePostIdRoute: ResolvePostIdRoute,
  TroubleMapRoute: TroubleMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
